EERIE_OCEAN_ELEM:
  type: mesh
  stream_id: 2137
  loss_weight: 1.0
  filenames:
  - /work/ab0995/a270225/data_transformation/eerie_ocean_3d_elements_daily.parq
  source:
  - avg_uoe_2.5m # ocean u velocity at 2.5m depth
  - avg_voe_2.5m # ocean v velocity at 2.5m depth
  target:
  - avg_uoe_2.5m
  - avg_voe_2.5m
  patch_size_deg: null
  sampling_mode: 'global_sparse' # loads given number of random points globally for each time step. 
  sample_points: 262144
  location_weight : cosine_latitude
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 32
  tokenize_spacetime : True
  max_num_targets: -1 
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    num_layers : 2
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1