#optional: if commented out all is taken care of by the default settings
# NB. global options apply to all run_ids 

#global_plotting_options:
#  regions: ["europe", "global"]
#  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
#  dpi_val : 300
#  fps: 2
#  ERA5:
#    marker_size: 2
#    scale_marker_size: 1
#    marker: "o"
#    add_healpix_grid: false
#    healpix_nside: 4
#    # alpha: 0.5
#    2t: 
#      vmin: 250
#      vmax: 300
#    10u:
#      vmin: -40
#      vmax: 40

evaluation:
  metrics  : ["rmse", "froct"]
  regions: ["global"]
  summary_plots : true
  ratio_plots : false
  heat_maps : false
  summary_dir: "./plots/"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: true
  bar_plots: false
  num_processes: 0  #options: int, "auto", 0 means no parallelism (default)
  # baseline: "ar40mckx"


default_streams:
  ERA5:
    channels: ["2t", "10v", "z_500", "t_850", "u_850", "v_850", "q_850"]
    evaluation:
      forecast_step: "1-3"  # Load all 40 steps - froct needs step N+1 to compute for step N
      sample: "all"
      ensemble: "all" #supported: "all", "mean", [0,1,2]
    plotting:
      sample: [1]
      forecast_step: "1-3" # Only plot steps 1-39 (step 40 has no next step for froct)
      ensemble: [0] #supported: "all", "mean", [0,1,2]
      plot_maps: false
      plot_bias: false
      plot_target: false
      plot_histograms: false
      plot_animations: false

run_ids :
  xjhqo5n6:
    label: "forecast model no MoE"
    results_base_dir : "./results/xjhqo5n6/"
    #NEW: if "streams" is not specified, the default streams are used

  # di32ugxz:
  #   label: "forecast model 16 blocks no MoE"
  #   results_base_dir : "./results/di32ugxz/"
  #   #NEW: if "streams" is not specified, the default streams are used
    
  b0caxynk:
    label: "MoE: All blocks, spatial"
    results_base_dir : "./results/b0caxynk/"
    #NEW: if "streams" is not specified, the default streams are used
  
  r8zc9aws:
    label: "MoE: All blocks, no spatial"
    results_base_dir : "./results/r8zc9aws/"
    #NEW: if "streams" is not specified, the default streams are used

  cdlxhcuf:
    label: "MoE: 2 blocks 16 experts,no spatial"
    results_base_dir : "./results/cdlxhcuf/"
    #NEW: if "streams" is not specified, the default streams are used

  # puvztgc3:
  #   label: "mul by 2"
  #   results_base_dir : "./results/puvztgc3/"
  #   #NEW: if "streams" is not specified, the default streams are used

  # t3ld9ki7:
  #   label: "mul by 5"
  #   results_base_dir : "./results/t3ld9ki7/"
  #   #NEW: if "streams" is not specified, the 