
freeze_modules: ".*encoder.*|.*latent_pre_norm.*|.*latent_heads.*"

# streams_directory: "./config/streams/era5_1deg/"
streams_directory: "config/streams/era5_nppatms_synop_finetuning"
streams: ???

general:

  # mutable parameters
  istep: 0
# config for training
training_config:
  
  # training_mode: "masking", "student_teacher", "latent_loss"
  # training_mode: ["student_teacher"]
  training_mode: ["masking"]

  num_mini_epochs: 8
  samples_per_mini_epoch: 4096
  shuffle: True

  start_date: 2014-01-01T00:00
  end_date: 2022-12-31T00:00

  time_window_step: 06:00:00
  time_window_len: 06:00:00

  window_offset_prediction : 0
  
  learning_rate_scheduling :
    lr_start: 1e-6
    lr_max: 5e-5
    lr_final_decay: 1e-6
    lr_final: 0.0
    num_steps_warmup: 512
    num_steps_cooldown: 512
    policy_warmup: "cosine"
    policy_decay: "constant"
    policy_cooldown: "linear"
    parallel_scaling_policy: "sqrt"

  optimizer:
    grad_clip: 1.0
    weight_decay: 0.1
    log_grad_norms: False
    adamw :
      # parameters are scaled by number of DDP workers
      beta1 : 0.975
      beta2 : 0.9875
      eps : 2e-08

  losses : {
      "student-teacher": {
        enabled: False,
      },
      "physical": {
        type: LossPhysical,
        enabled: True,
        weight: 1.0,
        loss_fcts: {
          "mse": {
            weight: 1.0,
            target_source_correspondence: { 0 : { 0 : "independent"} },
          },
        },
        target_and_aux_calc: "Physical",
    },
  }
  
  model_input: {
    "random_easy" : {
      # masking strategy: "random", "forecast"
      enabled: False,
    },
    "input" : {
      masking_strategy: "random",
      masking_strategy_config : { 
        rate : 1.0,
        rate_sampling: False
      },
    }
  }

  target_input: {
    "random_easy_target" : {
      enabled: False,
    },
    "target" : {
      masking_strategy: "random",
      masking_strategy_config : { 
        rate : 1.0,
        rate_sampling: False
      },
    }
  }

  # forecast :
  #   time_step: 00:00:00
  #   num_steps: 0
  #   policy: null


# validation config; full validation config is merge of training and validation config
validation_config: 

  samples_per_mini_epoch: 256
  shuffle: False

  start_date: 2022-10-01T00:00
  end_date: 2022-12-31T00:00
  
  # whether to track the exponential moving average of weights for validation
  validate_with_ema: 
    enabled : False
    ema_ramp_up_ratio: 0.09
    ema_halflife_in_thousands: 1e-3

  # parameters for validation samples that are written to disk
  output : {
    # number of samples that are written
    num_samples: 0,
    # write samples in normalized model space
    normalized_samples: False,
    # output streams to write; default all
    streams: ["NPPATMS"],
  }

  # run validation before training starts (mainly for model development)
  validate_before_training: 0
  
# test config; full test config is merge of validation and test config
# test config is used by default when running inference

# Tags for experiment tracking
# These tags will be logged in MLFlow along with completed runs for train, eval, val
# The tags are free-form, with the following rules:
# - tags should be primitive types (strings, numbers, booleans). NO lists or dictionaries
# - tags should not duplicate existing config entries.
# - try to reuse existing tags where possible. MLFlow does not like having too many unique tags
# - do not use long strings in values (less than 20 characters is a good rule of thumb, we may enforce this in the future)
wgtags:
  # The name of the organization of the person running the experiment.
  # This may be autofilled in the future. Expected values are lowercase strings 
  # e.g. "ecmwf", "cmcc", "metnor", "jsc", "escience"
  org: null
  # The Github issue corresponding to this run (number such as 1234)
  # Github issues are the central point when running experiment and contain 
  # links to hedgedocs, code branches, pull requests etc.
  # It is recommended to associate a run with a Github issue.
  issue: null
  # The name of the experiment. This is a distinctive codename for the experiment campaign being run.
  # This is expected to be the primary tag for comparing experiments in MLFlow, along with the
  # issue number.
  # Expected values are lowercase strings with no spaces, just underscores:
  # Examples: "rollout_ablation_grid"  
  exp: null
  # *** Experiment-specific tags ***
  # All extra tags (including lists, dictionaries, etc.) are treated 
  # as strings by mlflow, so treat all extra tags as simple string key: value pairs.
  grid: null