# JEPA deep-SSL sweep pipeline for launch-slurm.py
parallelize: false

stages:
  - name: multipretrain
    stage: train
    base_config: ./config/config_jepa_multi_data_all_years_swigluxsa.yml
    chain_jobs: 8
    nodes: 2

  - name: frcstft
    stage: train
    from_run_id: STAGE.multipretrain
    config_files:
      - ./config/config_jepa_multi_data_ft_forecast_all_years.yml
    chain_jobs: 6
    nodes: 2

  - name: frcstft8
    stage: train
    from_run_id: STAGE.frcstft
    config_files:
      - ./config/config_jepa_multi_data_ft_forecast_all_years_rollout.yml
    chain_jobs: 2
    nodes: 2
