train: 
  plot:
    c8i5plh4: 
      slurm_id: 1
      description: "Random, 15%, 32 epochs, forecast fine-tuning"

    l7u9mh6q:
      slurm_id: 3
      description: "Healpix, 15%, 32 epochs, forecast fine-tuning"

    dqruwnl4:
      slurm_id: 5
      description: "satellite_swath, 15%, 32 epochs, forecast fine-tuning"

    ewho5fyk:
      slurm_id: 7
      description: "satellite_swath_sparse, 15%, 32 epochs, forecast fine-tuning"

    jcokj5pg:
      slurm_id: 2
      description: "Mixed, ~ 15%, 32 epochs, forecast fine-tuning"