# (C) Copyright 2025 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.
#####################################

streams_directory: "./config/streams/raina_trans/"

freeze_modules: ".*global.*|.*local.*|.*adapter.*|.*q_cells.*|.*latent.*|.*ERA5.*"

general:

  # mutable parameters
  istep: 0
  rank: ???
  world_size: ???

  # local_rank, 
  # with_ddp,
  # data_path_*, 
  # model_path, 
  # run_path, 
  # path_shared_
  
  multiprocessing_method: "fork"

  desc: ""
  run_id: ???
  run_history: []

# config for training
training_config:
  
  # training_mode: "masking", "student_teacher", "latent_loss"
  training_mode: ["masking"]

  num_mini_epochs: 32

  start_date: 2014-01-01T00:00
  end_date: 2022-12-31T00:00
  
  learning_rate_scheduling :
    lr_start: 1e-6
    lr_max: 1e-4
    lr_final_decay: 2e-6
    lr_final: 0.0
    num_steps_warmup: 256
    num_steps_cooldown: 512
    policy_warmup: "cosine"
    policy_decay: "cosine"
    policy_cooldown: "linear"
    parallel_scaling_policy: "sqrt"

  forecast :
      time_step: 06:00:00
      offset: 1
      num_steps: 4
      policy: "fixed"