# (C) Copyright 2024 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

METOP_ABC_AVHRR_IASI :
  type : obs
  stream_id : 20
  filenames : ['observations-ea-ofb-0001-2007-2021-metop-a-iasi-radiances-v1.zarr', 'observations-ea-ofb-0001-2013-2023-metop-b-iasi-radiances-v1.zarr', 'observations-ea-ofb-0001-2019-2023-metop-c-iasi-radiances-v1.zarr']
  geoinfo_channels : ['cos_local_time', 'sin_local_time', 'cos_julian_day', 'sin_julian_day']
  loss_weight : 1.0
  masking_override :
    model_input :
      masking_strategy_config :
        rate: 1.0
  token_size : 512 # 256
  forcing: True
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords : 
    net : linear
    dim_embed : 256
  target_readout :
    num_layers : 2
    num_heads : 4
  pred_head : 
    ens_size : 1
    num_layers : 1

