# (C) Copyright 2025 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

# obs_types
# 0 : polar orbiting satellites
# 1 : geostationary satellites
# 2 : conventional observations

METOPB-IASI :
  type : obs
  stream_id : 3
  filenames : ['observations-ea-ofb-0001-2013-2023-metop-b-iasi-radiances-v1.zarr']
  loss_weight : 1.0
  diagnostic: True   # decoded only; not encoded (encoder was pretrained on ERA5 only)
  token_size : 32
  max_num_targets: -1
  embed :
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 128
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 512
  target_readout :
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1
